Fix windows 3.8 issue
snok/install-poetry pull request #95
Opened 2022-10-07 05:21 UTC by sondrelg

2022-10-07 05:28 UTC, miigotu commented
This wont fix #95, just makes sure we keep testing on 3.8.

If you set shell: bash as a default it will fail now, its a bug with the installl-poetry script itself.

2022-10-07 05:39 UTC, sondrelg commented
Yeah intending to reproduce, then fix, then merge. Just preemptively set the `Resolves #94` to it's there when we do get to the bottom of this 👍

2022-10-07 19:15 UTC, miigotu commented on main.sh
> +curl --ssl-no-revoke https://install.python-poetry.org/ --output "$installation_script"
-ssl-no-revoke is a windows only flag ^

2022-10-10 19:56 UTC, GuillaumeFalourd commented on main.sh
>  set -eo pipefail
Removing this line should resolve the issue without modifying anything else, as stated in https://github.com/snok/install-poetry/issues/94 (no idea why this is happening yet).

2022-10-10 19:56 UTC, GuillaumeFalourd requested changes

2022-10-10 19:56 UTC, GuillaumeFalourd commented on main.sh
>  set -eo pipefail
Removing this line should resolve the issue without modifying anything else, as stated in https://github.com/snok/install-poetry/issues/94 (no idea why this is happening yet).

2022-10-10 23:58 UTC, miigotu commented on .github/workflows/test.yml
> +  SUPPORTED_PYTHON_VERSIONS: '\"python-version\":[\"3.7\", \"3.8\", \"3.9\", \"3.10\", \"3.11.0-rc.1\"]'
3.11-rc.2 is out

2022-10-11 00:04 UTC, miigotu reviewed
3.11 is going to be released this month, we should probably test the latest rc2

2022-10-11 00:12 UTC, miigotu commented
On windows, I thought the path is `$path/Scripts/poetry.exe`
And Linux/Mac:
`$path/bin/poetry`

As this sits, on windows it tries `$path/Scripts/bin/poetry.exe`, is that correct?

2022-10-11 00:28 UTC, sondrelg commented on main.sh
>  set -eo pipefail
For some context, this line makes the action fail if something in the shell scripts fails. When removing this line, your [workflow](https://github.com/GuillaumeFalourd/install-poetry/actions/runs/3221930536/jobs/5270440194) passes, but if you look at the output of the installation step you can see that the installation actually failed.

I think we need to get to the bottom of why it's failing in the first place 👍

2022-10-11 00:34 UTC, miigotu commented
Could we add a temporary `[[ -f "$poetry_" ]] || echo "Poetry not found" && exit 1`
Here? Just for my piece of mind 😂
https://github.com/snok/install-poetry/compare/470a7d95f5d20f3d61351fc140809338bee18bdf..f9fc317f01f108f1b25d09cfbe8b58efa2b874d9#diff-f121df8f1f148ef72415f98dd27089a0e6cec3ec939840286358170e5e20c990R49

2022-10-11 00:45 UTC, miigotu commented on main.sh
>  set -eo pipefail
I think the installation fails when we go to call poetry with an absolute path, but it is successfully added to path by the install-poetry script.

So our install succeeds when no pipefail, but poetry config is not set from the inputs (that's where it fails, because the path we are calling is wrong)

Windows should be `../Scripts/poetry.exe, not `../Scripts/bin/poetry.exe`, Scripts is the equivalent of bin

2022-10-11 01:11 UTC, miigotu commented on main.sh
>  set -eo pipefail
I can't get branch 94 on my fork, but this is how the path setup should look:
https://github.com/miigotu/install-poetry/pull/1/files

2022-10-11 01:33 UTC, sondrelg commented on main.sh
>  set -eo pipefail
> I think the installation fails when we go to call poetry with an absolute path, but it is successfully added to path by the install-poetry script.
> 
> So our install succeeds when no pipefail, but poetry config is not set from the inputs (that's where it fails, because the path we are calling is wrong)
> 
> Windows should be `../Scripts/poetry.exe`, not `../Scripts/bin/poetry.exe`, Scripts is the equivalent of bin

Sounds sensible 👍 

> I can't get branch 94 on my fork, but this is how the path setup should look: https://github.com/miigotu/install-poetry/pull/1/files

You should have access to the repo directly @miigotu, so if you clone this repo directly you should be OK to fetch it 👍

2022-10-11 01:57 UTC, miigotu commented on main.sh
>  set -eo pipefail
Yeah I will. I'm having issues even with what I thought. It's setting bin instead of scripts even on windows for me it's frustrating.

2022-10-11 02:07 UTC, sondrelg commented on main.sh
>  set -eo pipefail
Yeah I noticed that too. Very strange.

Taking a look at the installation script internals to see if I can get to the bottom of the traceback, since it'a a bit confounding.

2022-10-11 02:07 UTC, miigotu commented
Scripts dir is symlinked to bin dir now:
![Screenshot_20221010-220443](https://user-images.githubusercontent.com/390379/194980938-5786de92-4fbb-417e-bee9-02d11ffe2ac2.png)

This is working now, some of the changes probably can be undone, but we don't need a special path for windows anymore:
https://github.com/miigotu/install-poetry/pull/1/files

2022-10-11 02:13 UTC, sondrelg commented
Interesting. So it basically looks like there are no OS-differences wrt. paths or shells for Windows/3.8. Removing the differences fixed the issue?

Will be interesting to see if that's also the case for other test matrix permutations.

2022-10-11 02:19 UTC, sondrelg commented
Seems the workflow still fails here, for https://github.com/snok/install-poetry/pull/95/commits/ed42a34da353387670a1c18a0e699875fbf195fa @miigotu 🤔 Am I missing something obvious?

2022-10-11 02:30 UTC, miigotu commented
@sondrelg yeah I see it's still failing even on mine. I've been doing this on my phone, about to get my laptop out 😂

2022-10-11 02:41 UTC, miigotu commented on main.sh
> +echo "VENV=.venv/bin/activate" >>"$GITHUB_ENV"
@sondrelg lol 😆

2022-10-11 03:07 UTC, miigotu commented on main.sh
>  set -eo pipefail
So there is the shortcut to bin outside the venv, for the poetry executable itself. No special path needed.

For the activate script, you have to use `.venv/scripts/activate`

2022-10-11 03:18 UTC, miigotu commented
@sondrelg it's passing now with the full matrix (with 3.8 included)

If you want to add a few tests maybe? It should be working.

2022-10-11 03:43 UTC, sondrelg commented
Yep I can do that 👍

2022-10-11 08:14 UTC, sondrelg commented
Happy with the changes here @miigotu? Moved all other changes, and a few extra, to #97

2022-10-12 01:18 UTC, merged